version: '3.8'

services:
  appointment_database:
    image: mysql:8.0
    container_name: appointment-mysql-c
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appointment_db
    ports:
      - "33063:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - appointment-network
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot || exit 1"]
#      interval: 15s
#      timeout: 10s
#      start_period: 40s
#      retries: 5

  appointment-service:
    build:
      context: ./appointment-service
      dockerfile: Dockerfile
    container_name: appointment-service
    ports:
      - "5001:5001"
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_PORT=33063
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=appointment_db
      - JWT_SECRET_KEY=your-secret-key-change-in-production
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - JWT_REFRESH_TOKEN_EXPIRE_DAYS=30
    depends_on:
      - appointment_database
#        condition: service_healthy
#    volumes:
#      - ./appointment-service:/app
    networks:
      - appointment-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql-data:

networks:
  appointment-network:
    driver: bridge
